// Load jimp
const Jimp = require('jimp')
const { MessageAttachment, MessageEmbed } = require('discord.js')
// Mapping function
function map (n, start1, stop1, start2, stop2) {
  return (n - start1) / (stop1 - start1) * (stop2 - start2) + start2
}

exports.run = (interaction, iterationMaximum, width, zoomLevel, mode, julia) => {
  return new Jimp(width, width, 0x000000ff, (err, image) => {
    for (let y = 0; y < width; y++) {
      for (let x = 0; x < width; x++) {
        let a = map(x, 0, width, -2 / zoomLevel, 2 / zoomLevel) - zoomLevel / (width / 100)
        let b = map(y, 0, width, -2 / zoomLevel, 2 / zoomLevel)

        const complexA = typeof julia !== 'undefined' ? Number(julia.split(';')[0]) : a
        const complexB = typeof julia !== 'undefined' ? Number(julia.split(';')[1]) : b

        let iterationAmount = 0
        for (; iterationAmount < iterationMaximum; iterationAmount++) {
          const cSqFirst = a * a - b * b
          const cSqSecond = 2 * a * b
          a = cSqFirst + complexA
          b = cSqSecond + complexB
          // a^2 + b^2 amounts to c^2 + c
          if (a * a + b * b > 4) break
        }

        const palettes = [parseInt(Math.ceil(2 * map(iterationAmount, 0, iterationMaximum, 0x10, 0x7f)).toString(16).repeat(3) + 'FF', 16),
          parseInt(Math.ceil(2 * map(iterationAmount, 0, iterationMaximum, 0x7f, 0x10)).toString(16).repeat(3) + 'FF', 16),
          parseInt(map(iterationAmount, 0, iterationMaximum, 0x10, 0xff).toString(16).repeat(3) + 'FF', 16),
          map(iterationAmount, 0, iterationMaximum, 0, 0xfffffff) + 0xff]

        const hexValue = palettes[mode - 1]
        image.setPixelColor(hexValue, x, y)
      }
    }
    // image.write(name, () => {
    //   interaction.reply({ files: [name] })
    // })
    image.getBuffer(Jimp.MIME_PNG, (error, buffer) => {
      const attachment = new MessageAttachment(buffer, 'fractalTemp.png')
      interaction.reply({
        embeds: [
          new MessageEmbed({
            title: 'Generated image:',
            color: 0x36393E,
            image: { url: 'attachment://fractalTemp.png' },
            footer: {
              text: 'Generated by Mandelbot v2.0.1',
              iconURL: 'https://cdn.discordapp.com/avatars/799707583627395112/a1962ca59e11af7c123e17480dcc5188.png?size=2048'
            }
          })
        ],
        files: [attachment]
      })
      if (error) {
        console.log(err)
      }
    })
    if (err) {
      console.log(err)
    }
  })
}
